DROP VIEW IF EXISTS braki_wyposazenia;
DROP VIEW IF EXISTS tygodniowa_placa;
DROP FUNCTION IF EXISTS mojplanlekcji(iddziecka numeric);
DROP FUNCTION IF EXISTS braki_wyposazenia();
DROP FUNCTION IF EXISTS wiecej_niz_zero(a numeric);
DROP TRIGGER IF EXISTS zamienNauczyciela ON Pracownicy;
DROP FUNCTION IF EXISTS zamien_nauczyciela();
DROP TRIGGER IF EXISTS uczynauczyciel ON przedmioty;
DROP FUNCTION IF EXISTS czy_nauczyciel();
DROP TRIGGER IF EXISTS usunnauczyciela ON pracownicy;
DROP FUNCTION IF EXISTS usun_nauczyciela();
DROP TRIGGER IF EXISTS dodaj_pracownika ON  pracownicy;
DROP FUNCTION IF EXISTS dodaj_pracownika();
DROP TRIGGER IF EXISTS dodaj_place ON Place;
DROP FUNCTION IF EXISTS dodaj_place();
DROP TRIGGER IF EXISTS "jednaLekcjaNaRaz" ON lekcje;
DROP FUNCTION IF EXISTS dodajlekcje();
DROP TRIGGER IF EXISTS "liczbaDzieci" ON uczniowie;
DROP FUNCTION IF EXISTS dodajdziecko();
DROP TRIGGER IF EXISTS usun_sale ON Sale;
DROP FUNCTION IF EXISTS usun_sale();
DROP TABLE if EXISTS Inwentaz;
DROP TABLE if EXISTS Obiekty;
DROP TABLE if EXISTS Lekcje;
DROP TABLE if EXISTS Przedmioty;
DROP TABLE if EXISTS Sale;
DROP TABLE if EXISTS Drogi_ewakuacyjne;
DROP TABLE if EXISTS Uczniowie;
DROP TABLE if EXISTS Klasy;
DROP TABLE if EXISTS Pracownicy;
DROP TABLE if EXISTS Place;
DROP SEQUENCE IF EXISTS pracownicy_id_seq;
